name: BackUp
version: '${version}'
main: robot7769.backup.BackupPlugin
api-version: '1.20'
author: Robot7769
commands:
  backup:
    description: Backup the server
    usage: /<command>
    permission: backup.backup
